//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JanSeredynskiLab4.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SEREK8;Initial Catalog=\"C:\\USERS\\LESZEK\\DOCUMENTS\\VISUAL STUDIO 2010\\" +
            "PROJECTS\\LESZEKROSZKOWSKI_LAB3_ZAD0\\LESZEKROSZKOWSKI_LAB3_ZAD0\\NORTHWND.MDF\";Int" +
            "egrated Security=True")]
        public string C__USERS_LESZEK_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_LESZEKROSZKOWSKI_LAB3_ZAD0_LESZEKROSZKOWSKI_LAB3_ZAD0_NORTHWND_MDF {
            get {
                return ((string)(this["C__USERS_LESZEK_DOCUMENTS_VISUAL_STUDIO_2010_PROJECTS_LESZEKROSZKOWSKI_LAB3_ZAD0_" +
                    "LESZEKROSZKOWSKI_LAB3_ZAD0_NORTHWND_MDF"]));
            }
        }
    }
}
