<?xml version="1.0" encoding="utf-8"?><Database Name="PizzaMenu" Class="DataClassesPizzaMenuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SEREK8;Initial Catalog=PizzaMenu;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PizzaMenuConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Pizza" Member="Pizzas">
    <Type Name="Pizza">
      <Column Name="PizzaMenuID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ingredient" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>